name = "bdzteam"
main = "src/worker.js"
compatibility_date = "2026-08-18"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
SUPABASE_URL = "https://nklukqriopezsoalnghm.supabase.co"
PUBLIC_ORIGIN = "https://bdzteam.vortexvn.workers.dev"
LINK4M_BASE_URL = "https://link4m.co/api-shorten/v2"
TRAFFICVN_BASE_URL = "https://trafficvn.com/apidevelop"
TURNSTILE_SITE_KEY = "0x4AAAAAAETrIC5FC0Mt25Qh"
ADMIN_USERNAME = "admin"
