const crypto=require('node:crypto');
const{json,env,supabaseFetch,createClaimToken,redeemClaimToken,shortenVuotLink}=require('../_lib');
function webhookSecret(){return crypto.createHash('sha256').update(env('ADMIN_SESSION_SECRET')+':telegram-webhook').digest('hex').slice(0,48)}
async function telegram(method,payload){const token=env('TELEGRAM_BOT_TOKEN');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);if(!r.ok||d?.ok===false)throw new Error(`Telegram ${method} failed: HTTP ${r.status}`);return d}
async function touchTelegramUser(tg){if(!tg?.id)return;await supabaseFetch('telegram_users',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({telegram_user_id:tg.id,username:tg.username||null,first_name:tg.first_name||null,last_name:tg.last_name||null,last_seen_at:new Date().toISOString()})})}
async function sendHelp(chatId){return telegram('sendMessage',{chat_id:chatId,text:'🔐 <b>BDZ KEY BOT</b>\n\nBấm <b>🔑 GET KEY</b> để nhận link vượt.\nSau khi vượt xong, sao chép token tại trang BDZ và gửi token đó lại cho bot để nhận KEY.',parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'🔑 GET KEY',callback_data:'get:key'}]]}})}
async function startKeyFlow(chatId,tg){const claim=await createClaimToken(tg,'quick',15);const tokenUrl=`https://bdzteam.vercel.app/token?token=${encodeURIComponent(claim.raw)}`;let shortenedUrl;try{shortenedUrl=await shortenVuotLink(tokenUrl)}catch(error){await supabaseFetch(`key_claim_tokens?id=eq.${Number(claim.row?.id||0)}&status=eq.PENDING`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'CANCELLED'})}).catch(()=>{});console.error(error);return telegram('sendMessage',{chat_id:chatId,text:'⚠️ Hiện không tạo được link vượt. Vui lòng thử lại sau ít phút.'})}return telegram('sendMessage',{chat_id:chatId,text:`🔗 <b>LINK GET KEY</b>\n\n${shortenedUrl}\n\n⏳ Link có hiệu lực trong 15 phút.\nSau khi vượt xong, sao chép token trên trang BDZ và gửi token đó lại cho bot.`,parse_mode:'HTML'})}
function normalizeSubmittedToken(text){const raw=String(text||'').trim();if(!raw)return '';const low=raw.toLowerCase();if(low.startsWith('token '))return raw.slice(6).trim();if(low.startsWith('token:'))return raw.slice(6).trim();return raw}
async function claimWithSubmittedToken(chatId,tg,text){const token=normalizeSubmittedToken(text);if(!token||token.length<20||token.length>128||!/^[A-Za-z0-9_-]+$/.test(token))return false;const result=await redeemClaimToken(token,tg?.id);if(!result?.ok){const messages={TOKEN_NOT_FOUND:'❌ Token không hợp lệ.',TOKEN_EXPIRED:'⏳ Token đã hết hạn. Hãy dùng /getkey để lấy link mới.',TOKEN_ALREADY_USED:'⚠️ Token này đã được sử dụng. Hãy dùng /getkey để lấy token mới.',TOKEN_OWNER_MISMATCH:'⛔ Token này không thuộc tài khoản Telegram của bạn.'};await telegram('sendMessage',{chat_id:chatId,text:messages[result?.reason]||'❌ Token không hợp lệ.'});return true}const key=result.key;return telegram('sendMessage',{chat_id:chatId,text:`✅ <b>GET KEY THÀNH CÔNG</b>\n\n<code>${key.key_code}</code>\n\n⏱️ Hạn: ${new Date(key.expires_at).toLocaleString('vi-VN')}`,parse_mode:'HTML'})}
async function handleMessage(chatId,text,tg){await touchTelegramUser(tg);const lower=String(text||'').trim().toLowerCase();if(lower==='/start'||lower==='/help')return sendHelp(chatId);if(lower==='/getkey'||lower==='/getquick')return startKeyFlow(chatId,tg);if(lower.startsWith('/'))return telegram('sendMessage',{chat_id:chatId,text:'❔ Lệnh không hợp lệ. Dùng /getkey để nhận key.'});const handled=await claimWithSubmittedToken(chatId,tg,text);if(!handled)return telegram('sendMessage',{chat_id:chatId,text:'📋 Hãy gửi token bạn nhận được tại trang /token, hoặc dùng /getkey để lấy link mới.'})}
async function answerCallback(q){const chatId=q?.message?.chat?.id;if(!chatId)return;await telegram('answerCallbackQuery',{callback_query_id:q.id});if(q.data==='get:key')await startKeyFlow(chatId,q.from)}
module.exports=async function handler(req,res){if(req.method!=='POST')return json(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'});if(String(req.headers['x-telegram-bot-api-secret-token']||'')!==webhookSecret())return json(res,401,{ok:false,error:'INVALID_WEBHOOK_SECRET'});try{const u=req.body||{};if(u.message?.chat?.id)await handleMessage(u.message.chat.id,u.message.text,u.message.from);if(u.callback_query)await answerCallback(u.callback_query);return json(res,200,{ok:true})}catch(error){console.error(error);try{const chatId=req.body?.message?.chat?.id||req.body?.callback_query?.message?.chat?.id;if(chatId)await telegram('sendMessage',{chat_id:chatId,text:'⚠️ Có lỗi khi xử lý yêu cầu. Vui lòng thử lại.'})}catch(sendError){console.error(sendError)}return json(res,500,{ok:false,error:'BOT_HANDLER_FAILED'})}};