const crypto=require('node:crypto');const{json,env,supabaseFetch,createClaimToken,redeemClaimToken,shortenVuotLink}=require('../_lib');
function webhookSecret(){return crypto.createHash('sha256').update(env('ADMIN_SESSION_SECRET')+':telegram-webhook').digest('hex').slice(0,48)}
async function telegram(method,payload){const token=env('TELEGRAM_BOT_TOKEN');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);if(!r.ok||d?.ok===false)throw new Error(`Telegram ${method} failed`);return d}
async function touch(tg){if(!tg?.id)return;await supabaseFetch('telegram_users',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({telegram_user_id:tg.id,username:tg.username||null,first_name:tg.first_name||null,last_name:tg.last_name||null,last_seen_at:new Date().toISOString()})})}
async function settings(){return(await supabaseFetch('bot_settings?select=*&limit=1'))?.[0]||{enabled:true,maintenance_mode:false,cooldown_seconds:20,token_ttl_minutes:15}}
async function blocked(id){return Boolean((await supabaseFetch(`bot_blocks?telegram_user_id=eq.${Number(id)}&select=telegram_user_id&limit=1`))?.length)}
async function cooldown(id,seconds){if(!seconds)return true;const r=await supabaseFetch('rpc/consume_rate_limit',{method:'POST',body:JSON.stringify({p_bucket:`tg:getkey:${Number(id)}`,p_limit:1,p_window_seconds:Number(seconds)})}).catch(()=>({allowed:true}));return r?.allowed!==false}
function menu(){return{inline_keyboard:[[{text:'🔑 LẤY KEY',callback_data:'get:key'}],[{text:'📊 TRẠNG THÁI',callback_data:'status:key'},{text:'🆕 BẢN MỚI',callback_data:'release:list'}],[{text:'🛡️ BẢO MẬT',callback_data:'security:info'},{text:'📖 HƯỚNG DẪN',callback_data:'help:show'}]]}}
async function home(chatId,tg){const first=String(tg?.first_name||'bạn').replace(/[<&>]/g,'');return telegram('sendMessage',{chat_id:chatId,text:`👋 <b>Xin chào ${first}!</b>\n\n🔐 <b>BDZ KEY SYSTEM</b>\n\nHệ thống cấp quyền truy cập ứng dụng theo thiết bị.\n\nBạn muốn làm gì?`,parse_mode:'HTML',reply_markup:menu()})}
async function help(chatId){return telegram('sendMessage',{chat_id:chatId,text:'📖 <b>HƯỚNG DẪN</b>\n\n1. Bấm LẤY KEY.\n2. Mở link được gửi.\n3. Hoàn tất trang vượt.\n4. Gửi claim token về bot.\n5. Nhận key.\n\nDùng TRẠNG THÁI để kiểm tra key.',parse_mode:'HTML',reply_markup:menu()})}
async function security(chatId){return telegram('sendMessage',{chat_id:chatId,text:'🛡️ <b>BẢO MẬT</b>\n\nToken chỉ lưu dạng hash và gắn Telegram ID.\nKey được kiểm tra ở server theo thiết bị, thời hạn và giới hạn.\nYêu cầu GET KEY có cooldown.',parse_mode:'HTML',reply_markup:menu()})}
async function status(chatId,tg){const rows=await supabaseFetch(`app_keys?telegram_user_id=eq.${Number(tg.id)}&order=created_at.desc&limit=1&select=key_code,status,expires_at,check_count,max_checks,activated_at`);const k=rows?.[0];if(!k)return telegram('sendMessage',{chat_id:chatId,text:'📊 <b>KEY STATUS</b>\n\nChưa có key.\n\nBấm LẤY KEY để bắt đầu.',parse_mode:'HTML',reply_markup:menu()});const expired=k.status==='EXPIRED'||(k.expires_at&&new Date(k.expires_at)<=new Date());const st=expired?'EXPIRED':k.status;const lim=Number(k.max_checks||0)===0?'∞':Number(k.max_checks);return telegram('sendMessage',{chat_id:chatId,text:`📊 <b>KEY STATUS</b>\n\nTrạng thái: <b>${st}</b>\nHạn: <b>${new Date(k.expires_at).toLocaleString('vi-VN')}</b>\nChecks: <b>${k.check_count||0} / ${lim}</b>\nThiết bị: <b>${k.activated_at?'Đã liên kết':'Chưa liên kết'}</b>\n\nKey: <code>${String(k.key_code)}</code>`,parse_mode:'HTML',reply_markup:menu()})}
async function releases(chatId){const rows=await supabaseFetch('bot_releases?enabled=eq.true&order=is_featured.desc,created_at.desc&limit=10&select=name,version,download_url,is_featured');if(!rows?.length)return telegram('sendMessage',{chat_id:chatId,text:'🆕 <b>BẢN MỚI</b>\n\nHiện chưa có bản phát hành mới.',parse_mode:'HTML',reply_markup:menu()});const text=rows.map((r,i)=>`${r.is_featured?'⭐ ':''}<b>${String(r.name).replace(/[<&>]/g,'')}</b>\nVersion: <b>${r.version}</b>`).join('\n\n');const buttons=rows.map(r=>[{text:`⬇️ ${String(r.name).slice(0,35)} ${r.version}`,url:r.download_url}]);return telegram('sendMessage',{chat_id:chatId,text:`🆕 <b>BẢN MỚI</b>\n\n${text}`,parse_mode:'HTML',reply_markup:{inline_keyboard:[...buttons,[{text:'↩️ MENU',callback_data:'menu:home'}]]}})}
async function startKey(chatId,tg){const s=await settings();if(s.enabled===false||s.maintenance_mode)return telegram('sendMessage',{chat_id:chatId,text:'🛠️ Bot đang bảo trì. Vui lòng thử lại sau.'});if(await blocked(tg.id))return telegram('sendMessage',{chat_id:chatId,text:'⛔ Tài khoản Telegram đang bị hạn chế.'});if(!(await cooldown(tg.id,s.cooldown_seconds)))return telegram('sendMessage',{chat_id:chatId,text:`⏳ Vui lòng chờ ${s.cooldown_seconds} giây rồi thử lại.`});const claim=await createClaimToken(tg,s.token_ttl_minutes);const tokenUrl=`https://bdzteam.vercel.app/token?token=${encodeURIComponent(claim.raw)}`;try{const short=await shortenVuotLink(tokenUrl);return telegram('sendMessage',{chat_id:chatId,text:`🔗 <b>LINK GET KEY</b>\n\n${short}\n\n⏳ Claim có hiệu lực ${s.token_ttl_minutes} phút.\nHoàn tất rồi gửi token lại cho bot.`,parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'📖 Hướng dẫn',callback_data:'help:show'}],[{text:'🆕 Bản mới',callback_data:'release:list'}]]}})}catch{await supabaseFetch(`key_claim_tokens?id=eq.${Number(claim.row?.id||0)}&status=eq.PENDING`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'CANCELLED'})}).catch(()=>{});return telegram('sendMessage',{chat_id:chatId,text:'⚠️ Không tạo được link lúc này. Hãy thử lại sau.'})}}
function normalize(t){return String(t||'').trim().replace(/^token\s*[: ]/i,'').trim()}
async function claim(chatId,tg,text){const token=normalize(text);if(!/^[A-Za-z0-9_-]{20,128}$/.test(token))return false;const result=await redeemClaimToken(token,tg.id);if(!result?.ok){const m={TOKEN_NOT_FOUND:'❌ Token không tồn tại.',TOKEN_EXPIRED:'⏳ Token đã hết hạn.',TOKEN_ALREADY_USED:'⚠️ Token đã được sử dụng.',TOKEN_OWNER_MISMATCH:'⛔ Token không thuộc tài khoản này.'};await telegram('sendMessage',{chat_id:chatId,text:m[result?.reason]||'❌ Token không hợp lệ.'});return true}const k=result.key;return telegram('sendMessage',{chat_id:chatId,text:`✅ <b>GET KEY THÀNH CÔNG</b>\n\n🔑 <code>${k.key_code}</code>\n📅 Hạn: <b>${new Date(k.expires_at).toLocaleString('vi-VN')}</b>`,parse_mode:'HTML',reply_markup:menu()})}
async function message(chatId,text,tg){await touch(tg);const low=String(text||'').trim().toLowerCase();if(low==='/start'||low==='/menu')return home(chatId,tg);if(low==='/help')return help(chatId);if(low==='/getkey')return startKey(chatId,tg);if(low==='/status')return status(chatId,tg);if(low==='/security')return security(chatId);if(low==='/release'||low==='/releases')return releases(chatId);if(low==='/id')return telegram('sendMessage',{chat_id:chatId,text:`🆔 Telegram ID: <code>${tg.id}</code>`,parse_mode:'HTML'});if(low.startsWith('/'))return telegram('sendMessage',{chat_id:chatId,text:'❔ Lệnh chưa được hỗ trợ. Dùng /start.'});if(await claim(chatId,tg,text))return;return telegram('sendMessage',{chat_id:chatId,text:'📋 Gửi claim token hoặc bấm LẤY KEY.',reply_markup:menu()})}
async function callback(q){const chatId=q?.message?.chat?.id;if(!chatId)return;await telegram('answerCallbackQuery',{callback_query_id:q.id});const tg=q.from;switch(q.data){case'get:key':return startKey(chatId,tg);case'status:key':return status(chatId,tg);case'release:list':return releases(chatId);case'security:info':return security(chatId);case'help:show':return help(chatId);case'menu:home':return home(chatId,tg)}}
module.exports=async function(req,res){if(req.method!=='POST')return json(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'});if(String(req.headers['x-telegram-bot-api-secret-token']||'')!==webhookSecret())return json(res,401,{ok:false,error:'INVALID_WEBHOOK_SECRET'});try{const u=req.body||{};if(u.message?.chat?.id)await message(u.message.chat.id,u.message.text,u.message.from);if(u.callback_query)await callback(u.callback_query);return json(res,200,{ok:true})}catch(error){console.error(error?.message||error);return json(res,500,{ok:false,error:'BOT_HANDLER_FAILED'})}};