const crypto=require('node:crypto');
const{json,env,supabaseFetch,createClaimToken,redeemClaimToken,shortenVuotLink}=require('../_lib');
function webhookSecret(){return crypto.createHash('sha256').update(env('ADMIN_SESSION_SECRET')+':telegram-webhook').digest('hex').slice(0,48)}
async function telegram(method,payload){const token=env('TELEGRAM_BOT_TOKEN');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);if(!r.ok||d?.ok===false)throw new Error(`Telegram ${method} failed: HTTP ${r.status}`);return d}
async function touch(tg){if(!tg?.id)return;await supabaseFetch('telegram_users',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({telegram_user_id:tg.id,username:tg.username||null,first_name:tg.first_name||null,last_name:tg.last_name||null,last_seen_at:new Date().toISOString()})})}
async function settings(){return (await supabaseFetch('bot_settings?select=*&limit=1'))?.[0]||{enabled:true,maintenance_mode:false,cooldown_seconds:20,token_ttl_minutes:15}}
async function blocked(id){return Boolean((await supabaseFetch(`bot_blocks?telegram_user_id=eq.${Number(id)}&select=telegram_user_id&limit=1`))?.length)}
async function cooldown(id,seconds){if(!seconds)return true;const r=await supabaseFetch('rpc/consume_rate_limit',{method:'POST',body:JSON.stringify({p_bucket:`tg:getkey:${Number(id)}`,p_limit:1,p_window_seconds:Number(seconds)})}).catch(()=>({allowed:true}));return r?.allowed!==false}
function menu(){return{inline_keyboard:[[{text:'🔑 LẤY KEY',callback_data:'get:key'}],[{text:'📊 TRẠNG THÁI',callback_data:'status:key'},{text:'🛡️ BẢO MẬT',callback_data:'security:info'}],[{text:'📖 HƯỚNG DẪN',callback_data:'help:show'}]]}}
async function home(chatId,tg){const s=await settings();const first=String(tg?.first_name||'bạn').replace(/[<&>]/g,'');return telegram('sendMessage',{chat_id:chatId,text:`👋 <b>Xin chào ${first}!</b>\n\n🔐 <b>BDZ KEY SYSTEM</b>\n\nBạn đang sử dụng hệ thống cấp quyền truy cập ứng dụng.\n\n━━━━━━━━━━━━━━\n🛡️ Key liên kết theo thiết bị\n⏳ Key có thời hạn\n📈 Có giới hạn kiểm tra\n🎟️ Claim token chỉ dùng một lần\n━━━━━━━━━━━━━━\n\nBạn muốn làm gì?`,parse_mode:'HTML',reply_markup:menu()})}
async function help(chatId){return telegram('sendMessage',{chat_id:chatId,text:'📖 <b>HƯỚNG DẪN</b>\n\n1. Bấm LẤY KEY.\n2. Mở link vượt được gửi về.\n3. Sao chép token trên trang BDZ.\n4. Gửi token nguyên vẹn lại cho bot.\n5. Bot trả key và thời hạn sử dụng.\n\nDùng STATUS để xem key hiện tại.',parse_mode:'HTML',reply_markup:menu()})}
async function security(chatId){return telegram('sendMessage',{chat_id:chatId,text:'🛡️ <b>BẢO MẬT</b>\n\n• Token được lưu dưới dạng hash.\n• Token gắn với Telegram ID và chỉ dùng một lần.\n• Key có trạng thái, hạn dùng và ràng buộc thiết bị.\n• Request GET KEY có cooldown để hạn chế spam.\n• Bot từ chối user bị block.\n\nKhông chia sẻ token cho người khác.',parse_mode:'HTML',reply_markup:menu()})}
async function status(chatId,tg){const rows=await supabaseFetch(`app_keys?telegram_user_id=eq.${Number(tg.id)}&order=created_at.desc&limit=1&select=key_code,key_scope,status,expires_at,check_count,max_checks,activated_at,device_id_hash`);const k=rows?.[0];if(!k)return telegram('sendMessage',{chat_id:chatId,text:'📊 <b>KEY STATUS</b>\n\nChưa tìm thấy key nào cho tài khoản này.\n\nBấm LẤY KEY để bắt đầu.',parse_mode:'HTML',reply_markup:menu()});const now=Date.now(),expired=k.status==='EXPIRED'||(k.expires_at&&new Date(k.expires_at).getTime()<=now);const statusText=expired?'EXPIRED':k.status;const checks=`${Number(k.check_count||0)} / ${Number(k.max_checks||0)===0?'∞':Number(k.max_checks)}`;return telegram('sendMessage',{chat_id:chatId,text:`📊 <b>KEY STATUS</b>\n\nTrạng thái: ${statusText==='ACTIVE'?'✅ ACTIVE':statusText}\nScope: <b>${String(k.key_scope||'').toUpperCase()}</b>\n\nHạn: <b>${new Date(k.expires_at).toLocaleString('vi-VN')}</b>\nThiết bị: ${k.device_id_hash||k.activated_at?'✅ Bound':'⚪ Chưa bind'}\nChecks: <b>${checks}</b>\n\nKey: <code>${String(k.key_code)}</code>`,parse_mode:'HTML',reply_markup:menu()})}
async function startKey(chatId,tg){const s=await settings();if(s.enabled===false||s.maintenance_mode)return telegram('sendMessage',{chat_id:chatId,text:'🛠️ Bot đang ở chế độ bảo trì. Vui lòng thử lại sau.'});if(await blocked(tg.id))return telegram('sendMessage',{chat_id:chatId,text:'⛔ Tài khoản Telegram của bạn đang bị hạn chế. Nếu đây là nhầm lẫn, dùng /support.'});if(!(await cooldown(tg.id,s.cooldown_seconds)))return telegram('sendMessage',{chat_id:chatId,text:`⏳ Bạn vừa yêu cầu GET KEY. Vui lòng chờ khoảng ${s.cooldown_seconds} giây rồi thử lại.`});const claim=await createClaimToken(tg,'quick',s.token_ttl_minutes);const tokenUrl=`https://bdzteam.vercel.app/token?token=${encodeURIComponent(claim.raw)}`;let short='';try{short=await shortenVuotLink(tokenUrl)}catch(e){await supabaseFetch(`key_claim_tokens?id=eq.${Number(claim.row?.id||0)}&status=eq.PENDING`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'CANCELLED'})}).catch(()=>{});return telegram('sendMessage',{chat_id:chatId,text:'⚠️ Không tạo được link vượt lúc này. Hệ thống đã bảo vệ yêu cầu của bạn, hãy thử lại sau.'})}return telegram('sendMessage',{chat_id:chatId,text:`🔗 <b>LINK GET KEY</b>\n\n${short}\n\n⏳ Claim có hiệu lực ${s.token_ttl_minutes} phút.\nSau khi hoàn tất, sao chép token tại trang BDZ và gửi token lại cho bot.`,parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'📖 Hướng dẫn',callback_data:'help:show'}]]}})}
function normalize(text){const raw=String(text||'').trim();return raw.replace(/^token\s*[: ]/i,'').trim()}
async function claim(chatId,tg,text){const token=normalize(text);if(!/^[A-Za-z0-9_-]{20,128}$/.test(token))return false;const result=await redeemClaimToken(token,tg.id);if(!result?.ok){const m={TOKEN_NOT_FOUND:'❌ Token không tồn tại.',TOKEN_EXPIRED:'⏳ Token đã hết hạn. Dùng LẤY KEY để tạo token mới.',TOKEN_ALREADY_USED:'⚠️ Token đã được sử dụng.',TOKEN_OWNER_MISMATCH:'⛔ Token không thuộc tài khoản Telegram này.'};await telegram('sendMessage',{chat_id:chatId,text:m[result?.reason]||'❌ Token không hợp lệ.'});return true}const k=result.key;return telegram('sendMessage',{chat_id:chatId,text:`✅ <b>GET KEY THÀNH CÔNG</b>\n\n🔑 <code>${k.key_code}</code>\n\n📅 Hạn: <b>${new Date(k.expires_at).toLocaleString('vi-VN')}</b>\n🏷️ Scope: <b>${String(k.key_scope).toUpperCase()}</b>\n\nDùng STATUS để xem trạng thái.`,parse_mode:'HTML',reply_markup:menu()})}
async function message(chatId,text,tg){await touch(tg);const low=String(text||'').trim().toLowerCase();if(low==='/start'||low==='/menu')return home(chatId,tg);if(low==='/help')return help(chatId);if(low==='/getkey'||low==='/getquick')return startKey(chatId,tg);if(low==='/status')return status(chatId,tg);if(low==='/security')return security(chatId);if(low==='/id')return telegram('sendMessage',{chat_id:chatId,text:`🆔 Telegram ID: <code>${tg.id}</code>`,parse_mode:'HTML'});if(low==='/support')return telegram('sendMessage',{chat_id:chatId,text:'🆘 <b>SUPPORT</b>\n\nHãy gửi vấn đề của bạn sau tin nhắn này. Admin sẽ kiểm tra khi có thể.',parse_mode:'HTML'});if(low.startsWith('/'))return telegram('sendMessage',{chat_id:chatId,text:'❔ Lệnh chưa được hỗ trợ. Dùng /start để mở menu.'});if(await claim(chatId,tg,text))return;return telegram('sendMessage',{chat_id:chatId,text:'📋 Hãy gửi claim token từ trang BDZ hoặc bấm LẤY KEY.',reply_markup:menu()})}
async function callback(q){const chatId=q?.message?.chat?.id;if(!chatId)return;await telegram('answerCallbackQuery',{callback_query_id:q.id});const tg=q.from;if(q.data==='get:key')return startKey(chatId,tg);if(q.data==='status:key')return status(chatId,tg);if(q.data==='security:info')return security(chatId);if(q.data==='help:show')return help(chatId)}
module.exports=async function handler(req,res){if(req.method!=='POST')return json(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'});if(String(req.headers['x-telegram-bot-api-secret-token']||'')!==webhookSecret())return json(res,401,{ok:false,error:'INVALID_WEBHOOK_SECRET'});try{const u=req.body||{};if(u.message?.chat?.id)await message(u.message.chat.id,u.message.text,u.message.from);if(u.callback_query)await callback(u.callback_query);return json(res,200,{ok:true})}catch(error){console.error(error?.message||error);try{const chatId=req.body?.message?.chat?.id||req.body?.callback_query?.message?.chat?.id;if(chatId)await telegram('sendMessage',{chat_id:chatId,text:'⚠️ Có lỗi tạm thời. Vui lòng thử lại sau.'})}catch{}return json(res,500,{ok:false,error:'BOT_HANDLER_FAILED'})}};