import {json,ipOf,sha256,rpc,setting,getSlots,shorten,banned,autoBanned,securityLog,ensureProducts,sb,consumeRateLimit,registerViolation,isBadUserAgent} from "./db.js";

const TURNSTILE_VERIFY_URL="https://challenges.cloudflare.com/turnstile/v0/siteverify";
export async function verifyTurnstileToken(token,request,env){
  const secret=String(env.TURNSTILE_SECRET_KEY||env.TURNSTILE_SECRET||'').trim();
  if(!secret)return {ok:false,status:503,message:'TURNSTILE_SECRET_KEY chưa được cấu hình trên Vercel.'};
  const value=String(token||'').trim();
  if(!value)return {ok:false,status:400,message:'Vui lòng hoàn thành xác minh Cloudflare Turnstile.'};
  try{
    const body=new URLSearchParams();
    body.set('secret',secret);
    body.set('response',value);
    const r=await fetch(TURNSTILE_VERIFY_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','accept':'application/json'},body:body.toString()});
    const text=await r.text();
    let d=null;try{d=text?JSON.parse(text):null}catch{}
    if(!r.ok||d?.success!==true){
      const codes=Array.isArray(d?.['error-codes'])?d['error-codes'].filter(x=>typeof x==='string').slice(0,3):[];
      return {ok:false,status:r.ok?403:503,message:codes.length?`Xác minh Cloudflare Turnstile thất bại (${codes.join(', ')}). Vui lòng thử lại.`:'Xác minh Cloudflare Turnstile không hợp lệ. Vui lòng thử lại.'};
    }
    return {ok:true};
  }catch(e){console.error('[turnstile]',e);return {ok:false,status:503,message:'Không thể kết nối hệ thống xác minh Cloudflare. Vui lòng thử lại.'}}
}
export async function siteData(env){const [name,slogan,contact]=await Promise.all([setting(env,"site_name","BDZTEAM"),setting(env,"site_slogan","Nền tảng quản lý và xác thực Key chạy trên hạ tầng đám mây"),setting(env,"contact_info","")]);return {site_name:name,site_slogan:slogan,contact_info:contact,logo_url:"https://files.catbox.moe/5tw3y4.jpg"}}
export async function publicStats(env){const now=encodeURIComponent(new Date().toISOString());const [a,b,c,d]=await Promise.all([sb(env,"keys?select=id&limit=10000").catch(()=>[]),sb(env,"keys?select=id&status=eq.ACTIVE&or=(expires_at.gt."+now+",expires_at.is.null)&limit=10000").catch(()=>[]),sb(env,"logs?select=id&limit=10000").catch(()=>[]),sb(env,"products?select=id&limit=10000").catch(()=>[])]);return {total_keys:a.length,active_keys:b.length,verifications:c.length,products:d.length}}
export async function keyMeta(request,env){const ip=ipOf(request),start=new Date();start.setUTCHours(0,0,0,0);const rows=await sb(env,"logs?select=id&ip_address=eq."+encodeURIComponent(ip)+"&result=eq.VALID&created_at=gte."+encodeURIComponent(start.toISOString())+"&limit=10000").catch(()=>[]);return json({ip,today_gets:rows.length})}
export async function products(env){return json({products:await ensureProducts(env)})}
export async function startGetKey(request,env){const b=await request.json().catch(()=>({})),pid=Number(b.product_id),ip=ipOf(request);if(!Number.isSafeInteger(pid)||pid<1)return json({error:"Sản phẩm không hợp lệ."},400);if(isBadUserAgent(request)){await registerViolation(env,ip,"bad_user_agent","get-key");return json({error:"Trình duyệt hoặc công cụ truy cập không được hỗ trợ."},403)}if(await banned(env,ip)||await autoBanned(env,ip))return json({error:"IP của bạn đã bị chặn tạm thời hoặc vĩnh viễn khỏi hệ thống."},403);if(!(await consumeRateLimit(env,"get-key",ip,300,5))){await registerViolation(env,ip,"rate_limit","get-key");return json({error:"Bạn đã yêu cầu quá nhiều lần. Vui lòng thử lại sau vài phút."},429)}const p=await sb(env,"products?select=id&id=eq."+pid+"&limit=1");if(!p?.length)return json({error:"Sản phẩm không tồn tại."},404);const client=await sha256(ip),token=crypto.randomUUID()+crypto.randomUUID();try{await rpc(env,"create_key_token",{p_token_hash:await sha256(token),p_product_id:pid,p_client_hash:client,p_ttl_seconds:900})}catch(e){await securityLog(env,"key_token_create_error",ip,e?.message||"");return json({error:"Không thể khởi tạo phiên lấy Key. Vui lòng thử lại."},503)}let dest=(new URL(request.url).origin)+"/key.html?step=3&token="+encodeURIComponent(token);const slots=Object.values(await getSlots(env)).filter(x=>x.enabled);if(!slots.length)return json({error:"Chưa có nguồn vượt link nào được bật. Vui lòng thử lại sau."},503);
const ordered=[...slots].sort((a,b)=>a.position-b.position);const attempted=[];let current=dest;
for(let i=ordered.length-1;i>=0;i--){const s=ordered[i];let reserved=false;try{const q=await rpc(env,"reserve_shortener_slot",{p_slot_position:s.position,p_client_hash:client,p_limit:s.quota});const ok=Array.isArray(q)?(q[0]?.reserve_shortener_slot??q[0]):(q?.reserve_shortener_slot??q);if(ok!==true&&ok!=="true"){attempted.push(`${s.provider}: quota`);continue}reserved=true;const next=await shorten(s,current,env);if(next){current=next;continue}}catch(e){attempted.push(`${s.provider}: ${String(e?.message||e).slice(0,180)}`);if(reserved)await rpc(env,"release_shortener_slot",{p_slot_position:s.position,p_client_hash:client}).catch(()=>{});continue}}
if(current===dest){await securityLog(env,"shortener_chain_unavailable",ip,attempted.join(" | ").slice(0,1000));return json({error:"Các nguồn vượt link hiện không khả dụng. Vui lòng thử lại sau vài giây."},503)}
return json({redirect:current})}
export async function claimKey(request,env){const b=await request.json().catch(()=>({})),token=String(b.token||'').trim(),ip=ipOf(request);if(!token)return json({error:'Token không hợp lệ.'},400);if(isBadUserAgent(request)){await registerViolation(env,ip,'bad_user_agent','claim-key');return json({error:'Trình duyệt hoặc công cụ truy cập không được hỗ trợ.'},403)}if(await banned(env,ip)||await autoBanned(env,ip))return json({error:'IP của bạn đã bị chặn tạm thời hoặc vĩnh viễn khỏi hệ thống.'},403);if(!(await consumeRateLimit(env,'claim-key',ip,300,10))){await registerViolation(env,ip,'rate_limit','claim-key');return json({error:'Bạn đã thao tác quá nhanh. Vui lòng thử lại sau vài phút.'},429)}const client=await sha256(ip);let rows;try{rows=await rpc(env,'claim_key_with_token',{p_token_hash:await sha256(token),p_client_hash:client,p_duration_hours:10,p_claimed_ip:ip})}catch(e){await securityLog(env,'key_claim_rpc_error',ip,e?.message||'');return json({error:'Không thể xác nhận Key lúc này. Vui lòng thử lại sau vài giây.'},503)}const row=Array.isArray(rows)?rows[0]:rows;if(!row?.key_code){await securityLog(env,'key_claim_invalid_or_expired',ip,'');await registerViolation(env,ip,'key_claim_invalid_token','');return json({error:'Token đã hết hạn hoặc đã được sử dụng. Vui lòng quay lại Bước 1 để lấy lại Key.'},403)}await sb(env,'logs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({key_code:row.key_code,product_id:Number(row.product_id),ip_address:ip,result:'VALID'})}).catch(()=>{});return json(row)}
export async function checkKey(request,env){const u=new URL(request.url);let key=u.searchParams.get('key')||'',product=u.searchParams.get('product')||'';if(request.method==='POST'){const b=await request.json().catch(()=>({}));key=b.key||key;product=b.product_slug||product}key=String(key).trim().toUpperCase();if(!key)return json({error:'Thiếu Key.'},400);const ip=ipOf(request);if(isBadUserAgent(request))return json({error:'Trình duyệt hoặc công cụ truy cập không được hỗ trợ.'},403);if(await banned(env,ip)||await autoBanned(env,ip))return json({error:'IP của bạn đã bị chặn.'},403);if(!(await consumeRateLimit(env,'check-key',ip,300,15))){await registerViolation(env,ip,'rate_limit','check-key');return json({error:'Bạn đã tra cứu quá nhiều lần. Vui lòng thử lại sau vài phút.'},429)}if(product){const r=await rpc(env,'verify_key',{p_key_code:key,p_product_slug:String(product).toLowerCase()});return json(Array.isArray(r)?r[0]:r)}const r=await rpc(env,'verify_key_public',{p_key_code:key});return json(Array.isArray(r)?r[0]:r)}
