function toRequest(req,url,bodyOverride){const headers=new Headers();for(const [k,v] of Object.entries(req.headers||{}))if(v!=null)headers.set(k,Array.isArray(v)?v.join(','):String(v));let body=bodyOverride;if(body===undefined&&!['GET','HEAD'].includes(req.method)){if(typeof req.body==='string')body=req.body;else if(req.body!==undefined)body=JSON.stringify(req.body)}return new Request(url,{method:req.method,headers,body})}
function send(res,r){res.statusCode=r.status;r.headers.forEach((v,k)=>res.setHeader(k,v));return r.arrayBuffer().then(b=>res.end(Buffer.from(b)))}
function jsonError(message,status=400,extra={}){return new Response(JSON.stringify({ok:false,error:String(message||'Yêu cầu không hợp lệ.')}),{status,headers:{'content-type':'application/json; charset=utf-8',...extra}})}
const METHODS={'/api/health':['GET'],'/api/session-check':['GET'],'/api/site':['GET'],'/api/stats':['GET'],'/api/key-meta':['GET'],'/api/products':['GET'],'/api/start-get-key':['POST'],'/api/v1/verify':['GET','POST','OPTIONS'],'/api/check-key':['GET','POST','OPTIONS'],'/api/verify':['GET','POST','OPTIONS'],'/api/claim-key':['POST'],'/api/register-sub-admin':['POST'],'/api/admin/login':['POST'],'/api/admin/recaptcha-config':['GET'],'/api/admin/auth-code':['POST'],'/api/admin/logout':['POST'],'/api/admin/me':['GET'],'/api/admin/dashboard':['GET'],'/api/admin/action':['POST'],'/api/admin/create-key':['POST'],'/api/admin/key-info':['GET'],'/api/admin/key-expiry':['POST']};
const USER_API_PATHS=new Set(['/api/stats','/api/key-meta','/api/products','/api/start-get-key','/api/v1/verify','/api/check-key','/api/verify','/api/claim-key']);
function clampInt(v,min,max,fallback){const n=Number(v);if(!Number.isFinite(n))return fallback;return Math.min(max,Math.max(min,Math.floor(n)))}
export default async function handler(req,res){
 const host=String(req.headers.host||'localhost');const base=`https://${host}`;const rawUrl=String(req.url||'/api');const fullUrl=new URL(rawUrl.startsWith('http')?rawUrl:`${base}${rawUrl}`);const pathname=fullUrl.pathname.replace(/\\+/g,'/').replace(/\/$/,'')||'/';const path=pathname.startsWith('/api/')?pathname:'/api';const request=toRequest(req,fullUrl.toString());const env=process.env;
 try{
  const db=await import('./db.js');
  const {json,clearAuth,ipOf,banned,autoBanned,getSession,setting,getSlots,securityLog,consumeRateLimit}=db;
  if(req.method==='OPTIONS')return send(res,new Response(null,{status:204,headers:{'access-control-allow-origin':req.headers.origin||'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,accept','access-control-allow-credentials':'true','cache-control':'no-store'}}));
  const allowed=METHODS[path];if(allowed&&!allowed.includes(String(req.method||'GET').toUpperCase()))return send(res,jsonError(`Method Not Allowed. ${allowed.join(' / ')} ${path} est requise.`,405,{'allow':allowed.join(', ')}));
  if(path==='/api/health')return send(res,json({ok:true,service:'bdzteam',status:'ok'}));
  if(path==='/api/session-check'&&req.method==='GET'){const ip=ipOf(request);if(await banned(env,ip))return send(res,json({ok:false,action:'ip_banned',message:'IP của bạn đã bị Quản trị viên khóa khỏi hệ thống.'},403,clearAuth()));if(await autoBanned(env,ip))return send(res,json({ok:false,action:'ip_banned',message:'IP của bạn đã bị tạm khóa do có hành vi bất thường.'},403,clearAuth()));const s=await getSession(request,env);if(!s)return send(res,json({ok:true,action:'none'}));if(s.r==='sub'){const k=env.SUPABASE_SECRET_KEY;if(!k)return send(res,json({ok:false,action:'server_error',message:'Hệ thống quản trị chưa sẵn sàng.'},503));const r=await fetch(env.SUPABASE_URL+'/rest/v1/sub_admins?select=status&id=eq.'+Number(s.id)+'&limit=1',{headers:{apikey:k,Authorization:'Bearer '+k,Accept:'application/json'}}).catch(()=>null);const rows=r?.ok?await r.json():[];if(!rows?.[0])return send(res,json({ok:false,action:'account_deleted',message:'Tài khoản không còn quyền truy cập.'},401,clearAuth()));if(rows[0].status!=='ACTIVE')return send(res,json({ok:false,action:'account_locked',message:'Tài khoản đã bị khóa.'},401,clearAuth()))}return send(res,json({ok:true,action:'none'}))}
  if(path==='/api/site'&&req.method==='GET'){const {siteData}=await import('./public_api.js');return send(res,json(await siteData(env)))}
  if(path==='/api/admin/recaptcha-config'&&req.method==='GET'){const siteKey=String(env.RECAPTCHA_SITE_KEY||'').trim();return send(res,json({ok:true,site_key:siteKey}))}
  if(USER_API_PATHS.has(path)){const maintenance=(await setting(env,'maintenance_enabled','false'))==='true';if(maintenance){const message=await setting(env,'maintenance_message','Website đang bảo trì. Vui lòng quay lại sau.');return send(res,json({ok:false,status:'MAINTENANCE',code:'SITE_MAINTENANCE',message},503,{'cache-control':'no-store'}))}}
  if(path==='/api/stats'&&req.method==='GET'){const {publicStats}=await import('./public_api.js');return send(res,json(await publicStats(env)))}
  if(path==='/api/key-meta'&&req.method==='GET'){const {keyMeta}=await import('./public_api.js');return send(res,await keyMeta(request,env))}
  if(path==='/api/products'&&req.method==='GET'){const {products}=await import('./public_api.js');return send(res,await products(env))}
  if(path==='/api/start-get-key'&&req.method==='POST'){const {startGetKey}=await import('./public_api.js');return send(res,await startGetKey(request,env))}
  if(['/api/v1/verify','/api/check-key','/api/verify'].includes(path)&&['GET','POST'].includes(String(req.method).toUpperCase())){const {verifyKeyByIp}=await import('./ip_verify.js');return send(res,await verifyKeyByIp(request,env))}
  if(path==='/api/claim-key'&&req.method==='POST'){const {claimKey}=await import('./public_api.js');return send(res,await claimKey(request,env))}
  if(path==='/api/register-sub-admin'&&req.method==='POST'){const {registerSubAdmin}=await import('./sub_admin_register.js');return send(res,await registerSubAdmin(request,env))}
  if(path==='/api/admin/login'&&req.method==='POST'){const {adminLogin}=await import('./admin_api.js');const raw=await request.text();let body={};try{body=raw?JSON.parse(raw):{}}catch{return send(res,jsonError('Dữ liệu đăng nhập không hợp lệ.',400))}return send(res,await adminLogin(toRequest(req,fullUrl.toString(),JSON.stringify(body)),env))}
  if(path==='/api/admin/auth-code'&&req.method==='POST'){const {adminAuthCode}=await import('./admin_api.js');return send(res,await adminAuthCode(request,env))}
  if(path==='/api/admin/logout'&&req.method==='POST')return send(res,json({ok:true},200,clearAuth()));
  if(path.startsWith('/api/admin/')){const {requireAdmin,dashboard,adminAction}=await import('./admin_api.js');const {handleKeyAdminAction}=await import('./key_admin_actions.js');const s=await requireAdmin(request,env);if(!s)return send(res,json({ok:false,error:'Chưa đăng nhập quản trị.'},401));
   if(path==='/api/admin/me'&&req.method==='GET')return send(res,json({ok:true,user:s.u,role:s.r}));
   if(path==='/api/admin/dashboard'&&req.method==='GET')return send(res,json(await dashboard(env,s)));
   if(path==='/api/admin/action'&&req.method==='POST'){const clone=request.clone();const handled=await handleKeyAdminAction(clone,env,s);if(handled)return send(res,handled);return send(res,await adminAction(request,env,s));}
   if(path==='/api/admin/create-key'&&req.method==='POST'){
    if(s.r!=='main')return send(res,json({ok:false,error:'Bạn không có quyền tạo Key Admin.'},403));
    const b=await request.json().catch(()=>({}));let code=String(b.key_code||'').trim().toUpperCase().replace(/[^A-Z0-9-]/g,'');if(!code)code='BDZ-'+crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase();const productId=Number(b.product_id),hours=clampInt(b.duration_hours,1,720,10);let maxDevices=clampInt(b.max_devices,0,1000,1);
    const product=(await db.sb(env,'products?id=eq.'+productId+'&select=id,name,slug&limit=1').catch(()=>[]))?.[0];if(!product)return send(res,json({ok:false,error:'Sản phẩm không hợp lệ.'},400));
    const exists=await db.sb(env,'keys?select=id&key_code=eq.'+encodeURIComponent(code)+'&limit=1').catch(()=>[]);if(exists?.length)return send(res,json({ok:false,error:'Key đã tồn tại.'},409));
    const expires=new Date(Date.now()+hours*3600000).toISOString();const created=await db.sb(env,'keys',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({key_code:code,product_id:productId,duration_hours:hours,status:'ACTIVE',expires_at:expires,key_scope:'ADMIN',max_devices:maxDevices,claimed_ip:null,claimed_at:null})});const row=Array.isArray(created)?created[0]:null;if(!row)return send(res,json({ok:false,error:'Không thể tạo Key.'},500));return send(res,json({ok:true,key_code:code,key_id:row.id,max_devices:maxDevices,product}));
   }
   if(path==='/api/admin/key-info'&&req.method==='GET'){
    const rows=await db.sb(env,'keys?select=id,key_code,max_devices,product_id,products(name,slug),key_device_bindings(device_id_hash,bound_ip,created_at,last_seen_at)&order=id.desc&limit=500').catch(()=>[]);return send(res,json({ok:true,keys:(rows||[]).map(k=>({...k,product_name:k.products?.name||null,product_slug:k.products?.slug||null,devices_used:Array.isArray(k.key_device_bindings)?k.key_device_bindings.length:0}))}));
   }
   if(path==='/api/admin/key-expiry'&&req.method==='POST'){
    const b=await request.json().catch(()=>({}));const id=Number(b.key_id),value=String(b.expires_at||'').trim();if(!Number.isSafeInteger(id)||id<1)return send(res,json({ok:false,error:'Key không hợp lệ.'},400));if(!value)return send(res,json({ok:false,error:'Thiếu thời gian hết hạn.'},400));const parsed=new Date(value);if(Number.isNaN(parsed.getTime())||parsed.getTime()<=Date.now())return send(res,json({ok:false,error:'Thời gian hết hạn không hợp lệ.'},400));const row=(await db.sb(env,'keys?select=id&id=eq.'+id+'&limit=1'))?.[0];if(!row)return send(res,json({ok:false,error:'Không tìm thấy Key.'},404));await db.sb(env,'keys?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({expires_at:parsed.toISOString(),status:'ACTIVE'})});return send(res,json({ok:true,expires_at:parsed.toISOString()}));
   }
  }
  return send(res,json({ok:false,error:'Not found',path},404));
 }catch(e){console.error('[vercel]',e);try{const db=await import('./db.js');return send(res,db.json({ok:false,error:String(e?.message||e).slice(0,500)},500))}catch{return send(res,new Response(JSON.stringify({ok:false,error:String(e?.message||e).slice(0,500)}),{status:500,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}}))}}
}
