const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
const ip=r=>r.headers.get('CF-Connecting-IP')||r.headers.get('X-Forwarded-For')?.split(',')[0]?.trim()||'0.0.0.0';
async function sha(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sb(env,path,init={}){const k=env.SUPABASE_SECRET_KEY;if(!k)throw Error('SUPABASE_SECRET_KEY chưa được cấu hình');const h=new Headers(init.headers);h.set('apikey',k);h.set('Authorization','Bearer '+k);h.set('Accept','application/json');if(init.body!==undefined)h.set('content-type','application/json');const r=await fetch(env.SUPABASE_URL.replace(/\/$/,'')+'/rest/v1/'+path.replace(/^\//,''),{...init,headers:h});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error('Supabase HTTP '+r.status);return d}
const rpc=(e,n,p)=>sb(e,'/rpc/'+n,{method:'POST',body:JSON.stringify(p)});
const safe=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)?x.href:''}catch{return ''}};
async function setting(e,k){const r=await sb(e,'settings?select=setting_value&setting_key=eq.'+encodeURIComponent(k)+'&limit=1');return r?.[0]?.setting_value||''}
function slots(raw){let v={};try{v=JSON.parse(raw||'{}')}catch{}const out=[];for(let p=1;p<=4;p++){const x=v[p]||v[String(p)]||{};const provider=String(x.provider||'').toLowerCase(),token=String(x.token||'').trim(),quota=Math.max(1,Math.min(100000,parseInt(x.quota||5)));if(['link4m','trafficvn'].includes(provider)&&token)out.push({position:p,provider,token,quota})}return out}
async function shorten(s,d,e){const base=s.provider==='link4m'?(e.LINK4M_BASE_URL||'https://link4m.co/api-shorten/v2'):(e.TRAFFICVN_BASE_URL||'https://trafficvn.com/apidevelop');const u=base.replace(/[?&]+$/,'')+'?api='+encodeURIComponent(s.token)+'&url='+encodeURIComponent(d);const r=await fetch(u,{headers:{accept:'application/json','user-agent':'BDZTEAM-Cloudflare/1.0'}});let x={};try{x=await r.json()}catch{}const c=[x.shortenedUrl,x.shortened_url,x.short_url,x.shorturl,x.url,x.link,x.data?.shortenedUrl,x.data?.short_url,x.data?.url,x.data?.link,x.result?.shortenedUrl,x.result?.short_url,x.result?.url];const short=c.map(safe).find(Boolean);if(!r.ok||!short)throw Error(s.provider+' không tạo được link rút gọn');return short}
async function products(e){return json({products:await sb(e,'products?select=id,name,slug&order=id.desc')})}
async function stats(e){const total=await sb(e,'keys?select=id',{headers:{Prefer:'count=exact'},method:'GET'}).then(()=>sb(e,'keys?select=id')).then(r=>r.length).catch(()=>0);const active=await sb(e,'keys?select=id&status=eq.ACTIVE&or=(expires_at.gt.'+encodeURIComponent(new Date().toISOString())+',expires_at.is.null)').then(r=>r.length).catch(()=>0);const logs=await sb(e,'logs?select=id').then(r=>r.length).catch(()=>0);const prods=await sb(e,'products?select=id').then(r=>r.length).catch(()=>0);return json({total_keys:total,active_keys:active,verifications:logs,products:prods})}
async function start(r,e){const b=await r.json().catch(()=>({})),pid=Number(b.product_id);if(!Number.isSafeInteger(pid)||pid<1)return json({error:'Sản phẩm không hợp lệ.'},400);const p=await sb(e,'products?select=id& id=eq.'+pid+'&limit=1'.replace(' ',''));if(!p?.length)return json({error:'Sản phẩm không tồn tại.'},404);const ss=slots(await setting(e,'shortener_slots')),client=await sha(ip(r)),tok=crypto.randomUUID()+crypto.randomUUID(),th=await sha(tok);await rpc(e,'create_key_token',{p_token_hash:th,p_product_id:pid,p_client_hash:client,p_ttl_seconds:900});let dest=(e.PUBLIC_ORIGIN||new URL(r.url).origin)+'/key.html?step=3&token='+encodeURIComponent(tok),reserved=[];try{for(let i=ss.length-1;i>=0;i--){const s=ss[i],q=await rpc(e,'reserve_shortener_slot',{p_slot_position:s.position,p_client_hash:client,p_limit:s.quota});const allowed=Array.isArray(q)?(q[0]?.reserve_shortener_slot??q[0]):q?.reserve_shortener_slot??q;if(allowed!==true&&allowed!=='true')throw Error('Vị trí '+s.position+' đã đạt giới hạn hôm nay.');reserved.push(s.position);dest=await shorten(s,dest,e)}}catch(x){for(const p of reserved)await rpc(e,'release_shortener_slot',{p_slot_position:p,p_client_hash:client}).catch(()=>{});return json({error:x.message||'Không tạo được chuỗi vượt link.'},503)}return json({redirect:dest})}
async function claim(r,e){const b=await r.json().catch(()=>({})),t=String(b.token||'').trim();if(!t)return json({error:'Token không hợp lệ.'},400);const id=await rpc(e,'verify_key_token',{p_token_hash:await sha(t),p_client_hash:await sha(ip(r)),p_consume:true});const pid=Array.isArray(id)?id[0]:id;const resolved=typeof pid==='object'&&pid?Object.values(pid)[0]:pid;if(!resolved)return json({error:'Token hết hạn, đã dùng hoặc không hợp lệ.'},403);const rows=await rpc(e,'claim_or_create_key',{p_product_id:Number(resolved),p_duration_hours:10,p_claimed_ip:ip(r)}),row=Array.isArray(rows)?rows[0]:rows;if(!row?.key_code)return json({error:'Không còn Key khả dụng.'},503);await sb(e,'logs',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify({key_code:row.key_code,product_id:Number(resolved),ip_address:ip(r),result:'VALID'})}).catch(()=>{});return json(row)}
async function check(r,e){const u=new URL(r.url),k=(u.searchParams.get('key')||'').trim();if(!k)return json({error:'Thiếu Key.'},400);const d=await rpc(e,'verify_key_public',{p_key_code:k.toUpperCase()});return json(Array.isArray(d)?d[0]:d)}
function assetHeaders(r){const h=new Headers(r.headers);h.set('X-Frame-Options','DENY');h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','strict-origin-when-cross-origin');h.set('Permissions-Policy','camera=(), microphone=(), geolocation=()');return h}
export default{async fetch(r,e){const u=new URL(r.url);try{if(r.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'}});if(u.pathname==='/health')return json({ok:true,service:'bdzteam-cloudflare',target:e.PUBLIC_ORIGIN||u.origin});if(u.pathname==='/api/products'&&r.method==='GET')return products(e);if(u.pathname==='/api/stats'&&r.method==='GET')return stats(e);if((u.pathname==='/api/check-key'||u.pathname==='/api/verify')&&r.method==='GET')return check(r,e);if(u.pathname==='/api/start-get-key'&&r.method==='POST')return start(r,e);if(u.pathname==='/api/claim-key'&&r.method==='POST')return claim(r,e);const a=await e.ASSETS.fetch(r);if(a.status!==404){const h=assetHeaders(a);return new Response(a.body,{status:a.status,statusText:a.statusText,headers:h})}return e.ASSETS.fetch(new Request(new URL('/index.html',r.url),r))}catch(x){console.error(x);return json({error:'Lỗi máy chủ. Vui lòng thử lại sau.'},500)}}}
