const crypto=require('node:crypto');
function json(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8');return res.end(JSON.stringify(body));}
function env(name,required=true){const value=process.env[name];if(required&&!value)throw new Error(`Missing environment variable: ${name}`);return value;}
function hash(value){return crypto.createHash('sha256').update(String(value)).digest('hex');}
function randomKey(length=16){const size=Math.max(12,Math.min(20,Number(length)||16));const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';let out='';for(let i=0;i<size;i++)out+=alphabet[crypto.randomInt(0,alphabet.length)];return out;}
function randomClaimToken(){return crypto.randomBytes(18).toString('base64url');}
function safeEqual(a,b){const aa=Buffer.from(String(a||'')),bb=Buffer.from(String(b||''));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);}
function sign(payload){const secret=env('ADMIN_SESSION_SECRET');const body=Buffer.from(JSON.stringify({...payload,exp:Date.now()+1000*60*60*24*7})).toString('base64url');const sig=crypto.createHmac('sha256',secret).update(body).digest('base64url');return `${body}.${sig}`;}
function verifySession(req){try{const raw=req.headers.cookie||'';const match=raw.match(/(?:^|; )bdz_admin=([^;]+)/);if(!match)return null;const[body,sig]=match[1].split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',env('ADMIN_SESSION_SECRET')).update(body).digest('base64url');if(!safeEqual(sig,expected))return null;const data=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));return Number(data.exp)>Date.now()?data:null;}catch{return null;}}
function setCookie(res,token){res.setHeader('Set-Cookie',`bdz_admin=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`);}
function clearCookie(res){res.setHeader('Set-Cookie','bdz_admin=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0');}
function firstIp(req){return String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||null;}
async function supabaseFetch(path,options={}){const base=env('SUPABASE_URL').replace(/\/$/,'');const key=env('SUPABASE_SERVICE_ROLE_KEY');const response=await fetch(`${base}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data=text;}if(!response.ok)throw new Error(data?.message||data?.hint||`Supabase HTTP ${response.status}`);return data;}
async function rpc(name,args={}){return supabaseFetch(`rpc/${name}`,{method:'POST',body:JSON.stringify(args)});}
async function createKey(telegramUser=null,durationHours=null,maxDevices=1,maxChecks=100,keyLength=16){const hours=Math.max(1,Math.min(8760,Number(durationHours)||24));const devices=Math.max(1,Math.min(100,Number(maxDevices)||1));const checks=Math.max(1,Math.min(1000000000,Number(maxChecks)||100));const now=new Date();const payload={key_code:randomKey(keyLength),status:'ACTIVE',duration_hours:hours,expires_at:new Date(now.getTime()+hours*3600000).toISOString(),max_devices:devices,max_checks:checks,check_count:0,telegram_user_id:telegramUser?.id??null,telegram_username:telegramUser?.username||null};const rows=await supabaseFetch('app_keys',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});if(telegramUser?.id!=null)await supabaseFetch('telegram_users',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({telegram_user_id:telegramUser.id,username:telegramUser.username||null,first_name:telegramUser.first_name||null,last_name:telegramUser.last_name||null,last_seen_at:now.toISOString()})});return rows?.[0]||payload;}
async function createClaimToken(telegramUser,ttlMinutes=15){const raw=randomClaimToken();const expiresAt=new Date(Date.now()+Math.max(1,Math.min(60,Number(ttlMinutes)||15))*60000).toISOString();const payload={token_hash:hash(raw),telegram_user_id:telegramUser?.id??null,telegram_username:telegramUser?.username||null,status:'PENDING',expires_at:expiresAt};const rows=await supabaseFetch('key_claim_tokens',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});return{raw,row:rows?.[0]||payload};}
async function redeemClaimToken(rawToken,telegramUserId){const tokenHash=hash(String(rawToken||'').trim());if(!tokenHash)return{ok:false,reason:'TOKEN_NOT_FOUND'};return rpc('redeem_claim_token',{p_token_hash:tokenHash,p_telegram_user_id:Number(telegramUserId)||0});}
async function getClaimToken(rawToken){const tokenHash=hash(String(rawToken||'').trim());if(!tokenHash)return null;const rows=await supabaseFetch(`key_claim_tokens?token_hash=eq.${encodeURIComponent(tokenHash)}&select=*&limit=1`);return rows?.[0]||null;}
async function reserveClaimToken(rawToken,telegramUserId){return redeemClaimToken(rawToken,telegramUserId);}
async function cancelClaimToken(id){if(!Number.isInteger(Number(id))||Number(id)<=0)return;await supabaseFetch(`key_claim_tokens?id=eq.${Number(id)}&status=eq.USED`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'PENDING',used_at:null})});}
async function fetchKeyByCode(keyCode){const code=encodeURIComponent(String(keyCode||'').trim());if(!code)return null;const rows=await supabaseFetch(`app_keys?key_code=eq.${code}&select=*&limit=1`);return rows?.[0]||null;}
async function recordCheck(item,result,deviceHash,req,appVersion){await supabaseFetch('key_checks',{method:'POST',body:JSON.stringify({key_id:item.id,device_id_hash:deviceHash,ip_address:firstIp(req),result,app_version:String(appVersion||'').slice(0,80)||null})});}
async function verifyAppKey(keyCode,deviceId,appVersion){return rpc('check_key',{p_key:String(keyCode||'').trim(),p_device_id:String(deviceId||'').trim(),p_app_version:String(appVersion||'').slice(0,80),p_ip:null});}
async function shortenVuotLink(longUrl){const config=(await supabaseFetch('shortener_configs?provider=eq.vuotlink&select=enabled,base_url,api_token&limit=1'))?.[0];const token=String(process.env.VUOTLINK_API_TOKEN||config?.api_token||'').trim();if(!token)throw new Error('VUOTLINK_API_TOKEN missing');if(config&&config.enabled===false)throw new Error('VuotLink đang tắt');const base=String(process.env.VUOTLINK_BASE_URL||config?.base_url||'https://vuotlink.xyz/api').replace(/\/$/,'');const endpoint=`${base}?api=${encodeURIComponent(token)}&url=${encodeURIComponent(longUrl)}`;const response=await fetch(endpoint,{method:'GET',headers:{Accept:'application/json'}});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null;}catch{}if(!response.ok)throw new Error(`VuotLink HTTP ${response.status}`);const shortenedUrl=data?.shortenedUrl||data?.shortened_url||data?.url||'';if(String(data?.status||'').toLowerCase()!=='success'||!shortenedUrl)throw new Error('VuotLink trả về dữ liệu không hợp lệ');return String(shortenedUrl);}
module.exports={json,env,hash,randomKey,randomClaimToken,safeEqual,sign,verifySession,setCookie,clearCookie,firstIp,supabaseFetch,rpc,createKey,createClaimToken,getClaimToken,reserveClaimToken,redeemClaimToken,cancelClaimToken,fetchKeyByCode,recordCheck,verifyAppKey,shortenVuotLink};
