const crypto=require('node:crypto');const{json,verifySession,supabaseFetch,randomKey}=require('./_lib');
const ip=req=>String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||null;const ua=req=>String(req.headers['user-agent']||'').slice(0,300)||null;const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');const body=req=>req.body||{};const int=(v,min,max,f)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):f};
const roles={OWNER:true,ADMIN:true};
async function ctx(req){const s=verifySession(req);if(!s?.sid||!s?.adminId)return null;const ss=await supabaseFetch(`admin_sessions?session_hash=eq.${encodeURIComponent(hash(s.sid))}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=id,admin_id&limit=1`).catch(()=>[]);if(!ss?.length)return null;const a=await supabaseFetch(`admins?id=eq.${Number(s.adminId)}&active=eq.true&select=id,username,role&limit=1`).catch(()=>[]);if(!a?.length||!roles[a[0].role])return null;return a[0]}
async function audit(actor,action,target,detail,req){await supabaseFetch('admin_audit',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({actor,action,target:String(target),detail,ip_address:ip(req),user_agent:ua(req)})}).catch(()=>{})}
function validKey(k){return/^[A-Za-z0-9]{12,20}$/.test(k)}
module.exports=async function(req,res){try{if(req.method!=='POST')return json(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'});const admin=await ctx(req);if(!admin)return json(res,401,{ok:false,error:'UNAUTHORIZED'});const b=body(req),action=String(b.action||'');
 if(action==='create'){const custom=String(b.key_code||'').trim();const key=custom||randomKey(int(b.key_length,12,20,16));if(!validKey(key))return json(res,400,{ok:false,error:'INVALID_KEY_FORMAT'});const hours=int(b.duration_hours,1,8760,24),checks=int(b.max_checks,0,1000000000,100),devices=int(b.max_devices,1,100,1),tgId=b.telegram_user_id?Number(b.telegram_user_id):null;const payload={key_code:key,key_fingerprint:hash(key),status:'ACTIVE',duration_hours:hours,expires_at:new Date(Date.now()+hours*3600000).toISOString(),telegram_user_id:Number.isFinite(tgId)?tgId:null,telegram_username:b.telegram_username?String(b.telegram_username).slice(0,120):null,max_devices:devices,max_checks:checks,check_count:0};let row=null;try{row=(await supabaseFetch('app_keys',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}))?.[0]||null}catch(e){if(String(e.message||'').toLowerCase().includes('duplicate'))return json(res,409,{ok:false,error:'KEY_ALREADY_EXISTS'});throw e}await audit(admin.username,'ADMIN_CREATE_KEY',hash(key),{custom:Boolean(custom),hours,checks,devices,tgId},req);return json(res,200,{ok:true,key:row})}
 if(action==='update'){const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});const patch={};if(b.key_code!==undefined){const key=String(b.key_code||'').trim();if(!validKey(key))return json(res,400,{ok:false,error:'INVALID_KEY_FORMAT'});patch.key_code=key;patch.key_fingerprint=hash(key)}if(b.duration_hours!==undefined){const h=int(b.duration_hours,1,8760,24);patch.duration_hours=h;patch.expires_at=new Date(Date.now()+h*3600000).toISOString()}if(b.max_checks!==undefined)patch.max_checks=int(b.max_checks,0,1000000000,0);if(b.max_devices!==undefined)patch.max_devices=int(b.max_devices,1,100,1);if(b.status!==undefined&&['ACTIVE','DISABLED','EXPIRED','REACTIVATED'].includes(b.status))patch.status=b.status;if(b.telegram_user_id!==undefined)patch.telegram_user_id=b.telegram_user_id?Number(b.telegram_user_id):null;if(b.telegram_username!==undefined)patch.telegram_username=b.telegram_username?String(b.telegram_username).slice(0,120):null;if(!Object.keys(patch).length)return json(res,400,{ok:false,error:'NO_CHANGES'});let row=null;try{row=(await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)}))?.[0]||null}catch(e){if(String(e.message||'').toLowerCase().includes('duplicate'))return json(res,409,{ok:false,error:'KEY_ALREADY_EXISTS'});throw e}await audit(admin.username,'ADMIN_UPDATE_KEY',id,{fields:Object.keys(patch)},req);return json(res,200,{ok:true,key:row})}
 if(action==='delete'){const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`app_keys?id=eq.${id}`,{method:'DELETE'});await audit(admin.username,'ADMIN_DELETE_KEY',id,{},req);return json(res,200,{ok:true})}
 if(action==='reset_device'){const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({device_id_hash:null,activated_device_id_hash:null,activated_ip_hash:null,activated_at:null})});await supabaseFetch(`key_checks?key_id=eq.${id}&result=eq.VALID`,{method:'DELETE'});await audit(admin.username,'ADMIN_RESET_DEVICE',id,{},req);return json(res,200,{ok:true})}
 if(action==='set_status'){const id=int(b.id,1,2147483647,0),status=String(b.status||'DISABLED');if(!id||!['ACTIVE','DISABLED','EXPIRED','LIMIT_REACHED','REACTIVATED'].includes(status))return json(res,400,{ok:false,error:'INVALID_STATUS'});await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status})});await audit(admin.username,'ADMIN_SET_KEY_STATUS',id,{status},req);return json(res,200,{ok:true})}
 return json(res,400,{ok:false,error:'UNKNOWN_ACTION'});
}catch(e){console.error(e?.message||e);return json(res,500,{ok:false,error:'SERVER_ERROR'})}};
