const crypto=require('node:crypto');
const{json,env,randomKey,sign,verifySession,setCookie,clearCookie,supabaseFetch}=require('./_lib');
const perms={OWNER:new Set(['read','keys','keys_reset','versions','releases','shortener','api','audit','admins','devices']),ADMIN:new Set(['read','keys','keys_reset','versions','releases','shortener','api','audit','admins','devices']),SUPPORT:new Set(['read','keys_reset','devices']),VIEWER:new Set(['read'])};
const body=req=>req.body||{};
const ip=req=>String(req.headers['x-forwarded-for']||req.headers['x-real-ip']||'').split(',')[0].trim()||null;
const ua=req=>String(req.headers['user-agent']||'').slice(0,300)||null;
const int=(v,min,max,fallback)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):fallback};
const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const passwordHash=password=>{const salt=crypto.randomBytes(16).toString('base64url');return`scrypt$${salt}$${crypto.scryptSync(String(password),salt,64).toString('base64url')}`};
const passwordOk=(password,stored)=>{try{const[,salt,key]=String(stored||'').split('$');if(!salt||!key)return false;const got=crypto.scryptSync(String(password),salt,64);return crypto.timingSafeEqual(got,Buffer.from(key,'base64url'))}catch{return false}};
async function audit(actor,action,target,detail={},req){await supabaseFetch('admin_audit',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({action,actor,target:target==null?null:String(target),detail,ip_address:ip(req),user_agent:ua(req)})}).catch(()=>{})}
async function adminSession(req){const s=verifySession(req);if(!s?.sid||!s?.adminId)return null;const rows=await supabaseFetch(`admin_sessions?session_hash=eq.${encodeURIComponent(hash(s.sid))}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=id,admin_id&limit=1`).catch(()=>[]);if(!rows?.length)return null;const admins=await supabaseFetch(`admins?id=eq.${Number(s.adminId)}&active=eq.true&select=id,username,display_name,role,active,avatar_url,language,timezone,created_at,last_login_at,last_ip,last_user_agent&limit=1`).catch(()=>[]);if(!admins?.length)return null;await supabaseFetch(`admin_sessions?id=eq.${rows[0].id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_seen_at:new Date().toISOString()})}).catch(()=>{});return{session:s,admin:admins[0],sessionId:rows[0].id}}
async function createSession(admin,req){const sid=crypto.randomBytes(32).toString('base64url');const expires=new Date(Date.now()+7*24*3600000).toISOString();await supabaseFetch('admin_sessions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({admin_id:admin.id,session_hash:hash(sid),expires_at:expires,ip_address:ip(req),user_agent:ua(req)})});setCookie(req.res,sign({sub:admin.username,adminId:admin.id,role:admin.role,sid}))}
async function ensureOwner(username,password,req){const rows=await supabaseFetch(`admins?username=eq.${encodeURIComponent(username)}&select=*&limit=1`).catch(()=>[]);if(rows?.[0])return rows[0].active&&passwordOk(password,rows[0].password_hash)?rows[0]:null;const created=await supabaseFetch('admins',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({username,display_name:username,role:'OWNER',password_hash:passwordHash(password),last_login_at:new Date().toISOString(),last_ip:ip(req),last_user_agent:ua(req)})});return created?.[0]||null}
const allow=(role,p)=>!!perms[role]?.has(p);
const keyStatuses=['CREATED','ACTIVE','DISABLED','EXPIRED','LIMIT_REACHED','REACTIVATED'];
module.exports=async function(req,res){req.res=res;try{
 if(req.method==='POST'&&body(req).action==='login'){const b=body(req),username=String(b.username||'').trim(),password=String(b.password||'');if(!username||!password)return json(res,400,{ok:false,error:'INVALID_LOGIN'});const rl=await supabaseFetch('rpc/consume_rate_limit',{method:'POST',body:JSON.stringify({p_bucket:'admin-login:'+hash(ip(req)||'unknown'),p_limit:8,p_window_seconds:300})}).catch(()=>null);if(rl?.allowed===false)return json(res,429,{ok:false,error:'LOGIN_RATE_LIMITED'});let admin=null;if(username===env('ADMIN_USERNAME')&&password===env('ADMIN_PASSWORD'))admin=await ensureOwner(username,password,req);if(!admin){const rows=await supabaseFetch(`admins?username=eq.${encodeURIComponent(username)}&active=eq.true&select=*&limit=1`).catch(()=>[]);if(rows?.[0]&&passwordOk(password,rows[0].password_hash))admin=rows[0]}if(!admin)return json(res,401,{ok:false,error:'INVALID_LOGIN'});await supabaseFetch(`admins?id=eq.${admin.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_login_at:new Date().toISOString(),last_ip:ip(req),last_user_agent:ua(req)})}).catch(()=>{});await createSession(admin,req);await audit(admin.username,'LOGIN',admin.id,{},req);return json(res,200,{ok:true,user:admin.username,role:admin.role,display_name:admin.display_name})}
 if(req.method==='POST'&&body(req).action==='logout'){const s=verifySession(req);if(s?.sid)await supabaseFetch(`admin_sessions?session_hash=eq.${encodeURIComponent(hash(s.sid))}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})}).catch(()=>{});clearCookie(res);return json(res,200,{ok:true})}
 const ctx=await adminSession(req);if(!ctx)return json(res,401,{ok:false,error:'UNAUTHORIZED'});const actor=ctx.admin.username,role=ctx.admin.role;
 if(req.method==='GET'){const today=new Date();today.setHours(0,0,0,0);const[allKeys,checks,devices,tokens,audits,admins,sessions,shorteners,versions,releases]=await Promise.all([
 supabaseFetch('app_keys?select=id,key_code,key_fingerprint,status,duration_hours,expires_at,device_id_hash,activated_device_id_hash,max_devices,max_checks,activated_at,last_checked_at,check_count,created_at&order=created_at.desc&limit=1000').catch(()=>[]),
 supabaseFetch('key_checks?select=id,key_id,result,app_version,ip_address,created_at&order=created_at.desc&limit=1500').catch(()=>[]),
 allow(role,'devices')?supabaseFetch('app_key_devices?select=id,key_id,device_hash,first_seen_at,last_seen_at&order=last_seen_at.desc&limit=1500').catch(()=>[]):Promise.resolve([]),
 supabaseFetch('key_claim_tokens?select=id,status,expires_at,used_at,created_at&order=created_at.desc&limit=500').catch(()=>[]),
 allow(role,'audit')?supabaseFetch('admin_audit?select=id,action,actor,target,detail,ip_address,user_agent,created_at&order=created_at.desc&limit=500').catch(()=>[]):Promise.resolve([]),
 allow(role,'admins')?supabaseFetch('admins?select=id,username,display_name,role,active,created_at,last_login_at,last_ip,last_user_agent&order=created_at.desc&limit=100').catch(()=>[]):Promise.resolve([]),
 allow(role,'admins')?supabaseFetch(`admin_sessions?admin_id=eq.${ctx.admin.id}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=id,created_at,last_seen_at,expires_at,ip_address,user_agent&order=last_seen_at.desc&limit=50`).catch(()=>[]):Promise.resolve([]),
 allow(role,'shortener')?supabaseFetch('shortener_configs?select=id,provider,enabled,base_url,sort_order,updated_at&order=sort_order.asc,provider.asc').catch(()=>[]):Promise.resolve([]),
 supabaseFetch('app_versions?select=id,version,version_code,display_name,status,is_latest,update_message,download_url,released_at,created_at,updated_at&order=version_code.desc&limit=100').catch(()=>[]),
 supabaseFetch('bot_releases?select=id,name,version,download_url,enabled,is_featured,created_at,updated_at&order=created_at.desc&limit=100').catch(()=>[])]);const active=(allKeys||[]).filter(k=>['ACTIVE','REACTIVATED'].includes(k.status));return json(res,200,{ok:true,user:actor,role,admin:ctx.admin,keys:allKeys||[],checks:checks||[],devices:devices||[],claim_tokens:tokens||[],audit:audits||[],admins:admins||[],sessions:sessions||[],shorteners:shorteners||[],versions:versions||[],releases:releases||[],stats:{total_keys:allKeys?.length||0,active_keys:active.length,total_devices:devices?.length||0,total_checks:checks?.length||0,checks_today:(checks||[]).filter(x=>new Date(x.created_at)>=today).length,claims:tokens?.length||0,failed_checks:(checks||[]).filter(x=>x.result!=='VALID').length},api:{provider:'Supabase',rpc:'check_key',version_rpc:'check_app_version',endpoint:`${env('SUPABASE_URL')}/rest/v1/rpc/check_key`,version_endpoint:`${env('SUPABASE_URL')}/rest/v1/rpc/check_app_version`,method:'POST',body:{p_key:'KEY',p_device_id:'DEVICE_ID',p_app_version:'V1.0.0',p_ip:'CLIENT_IP'}}})}
 if(req.method!=='POST')return json(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'});const b=body(req),action=String(b.action||'');
 if(action==='create_key'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const hours=int(b.duration_hours,1,8760,24),devicesMax=int(b.max_devices,1,100,1),checksMax=int(b.max_checks,0,1000000000,100),length=int(b.key_length,12,20,16),custom=String(b.key_code||'').trim();if(custom&&!/^[A-Za-z0-9]{12,20}$/.test(custom))return json(res,400,{ok:false,error:'INVALID_KEY'});for(let i=0;i<10;i++){const code=custom||randomKey(length);try{const created=await supabaseFetch('app_keys',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({key_code:code,key_fingerprint:hash(code),status:'ACTIVE',duration_hours:hours,expires_at:new Date(Date.now()+hours*3600000).toISOString(),max_devices:devicesMax,max_checks:checksMax,check_count:0})});await audit(actor,'CREATE_KEY',hash(code),{hours,devices:devicesMax,checks:checksMax},req);return json(res,200,{ok:true,key:created?.[0]})}catch(e){if(custom||!/duplicate/i.test(String(e.message||'')))throw e}}throw new Error('KEY_GENERATION_FAILED')}
 if(action==='update_key'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});const patch={};if(b.key_code!==undefined){const code=String(b.key_code||'').trim();if(!/^[A-Za-z0-9]{12,20}$/.test(code))return json(res,400,{ok:false,error:'INVALID_KEY'});patch.key_code=code;patch.key_fingerprint=hash(code)}if(b.duration_hours!==undefined){const h=int(b.duration_hours,1,8760,24);patch.duration_hours=h;patch.expires_at=new Date(Date.now()+h*3600000).toISOString()}if(b.max_devices!==undefined)patch.max_devices=int(b.max_devices,1,100,1);if(b.max_checks!==undefined)patch.max_checks=int(b.max_checks,0,1000000000,100);if(keyStatuses.includes(b.status))patch.status=b.status;if(!Object.keys(patch).length)return json(res,400,{ok:false,error:'NO_CHANGES'});const updated=await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});await audit(actor,'UPDATE_KEY',id,{patch:{...patch,key_fingerprint:patch.key_fingerprint?'changed':undefined}},req);return json(res,200,{ok:true,key:updated?.[0]||null})}
 if(action==='reset_device'){if(!allow(role,'keys_reset'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({device_id_hash:null,activated_device_id_hash:null,activated_ip_hash:null,activated_at:null})});await supabaseFetch(`app_key_devices?key_id=eq.${id}`,{method:'DELETE'}).catch(()=>{});await audit(actor,'RESET_DEVICE',id,{},req);return json(res,200,{ok:true})}
 if(action==='reset_checks'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({check_count:0,status:'ACTIVE'})});await audit(actor,'RESET_CHECKS',id,{},req);return json(res,200,{ok:true})}
 if(action==='set_status'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});const status=keyStatuses.includes(b.status)?b.status:'DISABLED';await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status})});await audit(actor,'SET_KEY_STATUS',id,{status},req);return json(res,200,{ok:true})}
 if(action==='delete_key'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`app_keys?id=eq.${id}`,{method:'DELETE'});await audit(actor,'DELETE_KEY',id,{},req);return json(res,200,{ok:true})}
 if(action==='create_version'){if(!allow(role,'versions'))return json(res,403,{ok:false,error:'FORBIDDEN'});const version=String(b.version||'').trim().toUpperCase(),code=int(b.version_code,1,2147483647,0);if(!/^V[0-9A-Za-z][0-9A-Za-z._-]{0,63}$/.test(version)||!code)return json(res,400,{ok:false,error:'INVALID_VERSION'});if(b.is_latest===true)await supabaseFetch('app_versions?is_latest=eq.true',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_latest:false})}).catch(()=>{});const payload={version,version_code:code,display_name:String(b.display_name||version).trim().slice(0,120),status:String(b.status||'ACTIVE').toUpperCase(),is_latest:Boolean(b.is_latest),update_message:String(b.update_message||'').trim().slice(0,500)||null,download_url:String(b.download_url||'').trim()||null,released_at:new Date().toISOString()};const created=await supabaseFetch('app_versions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});await audit(actor,'CREATE_VERSION',version,{version_code:code},req);return json(res,200,{ok:true,version:created?.[0]||null})}
 if(action==='update_version'){if(!allow(role,'versions'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});const patch={};if(b.display_name!==undefined)patch.display_name=String(b.display_name||'').trim().slice(0,120);if(b.status!==undefined)patch.status=String(b.status||'ACTIVE').toUpperCase();if(b.update_message!==undefined)patch.update_message=String(b.update_message||'').trim().slice(0,500)||null;if(b.download_url!==undefined)patch.download_url=String(b.download_url||'').trim()||null;if(b.is_latest===true){await supabaseFetch('app_versions?is_latest=eq.true',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_latest:false})}).catch(()=>{});patch.is_latest=true}if(!Object.keys(patch).length)return json(res,400,{ok:false,error:'NO_CHANGES'});const updated=await supabaseFetch(`app_versions?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});await audit(actor,'UPDATE_VERSION',id,{patch},req);return json(res,200,{ok:true,version:updated?.[0]||null})}
 if(action==='delete_version'){if(!allow(role,'versions'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`app_versions?id=eq.${id}`,{method:'DELETE'});await audit(actor,'DELETE_VERSION',id,{},req);return json(res,200,{ok:true})}
 if(action==='create_release'){if(!allow(role,'releases'))return json(res,403,{ok:false,error:'FORBIDDEN'});const payload={name:String(b.name||'').trim().slice(0,150),version:String(b.version||'').trim().slice(0,80)||null,download_url:String(b.download_url||'').trim(),enabled:b.enabled!==false,is_featured:Boolean(b.is_featured)};if(!payload.name||!payload.download_url)return json(res,400,{ok:false,error:'INVALID_RELEASE'});const created=await supabaseFetch('bot_releases',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});await audit(actor,'CREATE_RELEASE',payload.name,{version:payload.version},req);return json(res,200,{ok:true,release:created?.[0]||null})}
 if(action==='update_release'){if(!allow(role,'releases'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});const patch={};if(b.name!==undefined)patch.name=String(b.name||'').trim().slice(0,150);if(b.version!==undefined)patch.version=String(b.version||'').trim().slice(0,80)||null;if(b.download_url!==undefined)patch.download_url=String(b.download_url||'').trim();if(b.enabled!==undefined)patch.enabled=Boolean(b.enabled);if(b.is_featured!==undefined)patch.is_featured=Boolean(b.is_featured);if(!Object.keys(patch).length)return json(res,400,{ok:false,error:'NO_CHANGES'});const updated=await supabaseFetch(`bot_releases?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});await audit(actor,'UPDATE_RELEASE',id,{patch},req);return json(res,200,{ok:true,release:updated?.[0]||null})}
 if(action==='delete_release'){if(!allow(role,'releases'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`bot_releases?id=eq.${id}`,{method:'DELETE'});await audit(actor,'DELETE_RELEASE',id,{},req);return json(res,200,{ok:true})}
 if(action==='save_shortener'){if(!allow(role,'shortener'))return json(res,403,{ok:false,error:'FORBIDDEN'});const provider=String(b.provider||'vuotlink').trim().toLowerCase();if(!provider)return json(res,400,{ok:false,error:'INVALID_PROVIDER'});const enabled=Boolean(b.enabled),baseUrl=String(b.base_url||'').trim();const token=String(b.api_token||'').trim();const existing=await supabaseFetch(`shortener_configs?provider=eq.${encodeURIComponent(provider)}&select=id&limit=1`).catch(()=>[]);if(existing?.[0]?.id)await supabaseFetch(`shortener_configs?id=eq.${existing[0].id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({...({enabled,base_url:baseUrl||null,sort_order:int(b.sort_order,1,100,1),updated_at:new Date().toISOString()}),...(token?{api_token:token}:{})})});else await supabaseFetch('shortener_configs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({provider,enabled,base_url:baseUrl||null,api_token:token||null,sort_order:int(b.sort_order,1,100,1)})});await audit(actor,'SAVE_SHORTENER',provider,{enabled,baseUrl,tokenChanged:Boolean(token)},req);return json(res,200,{ok:true})}
 if(action==='revoke_session'){if(!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=String(b.id||'');if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`admin_sessions?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});await audit(actor,'REVOKE_SESSION',id,{},req);return json(res,200,{ok:true})}
 if(action==='create_admin'){if(!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});const username=String(b.username||'').trim(),password=String(b.password||'');const display=String(b.display_name||username).trim();const newRole=['OWNER','ADMIN','SUPPORT','VIEWER'].includes(String(b.role||'').toUpperCase())?String(b.role).toUpperCase():'VIEWER';if(!/^[A-Za-z0-9_.-]{3,40}$/.test(username)||password.length<8)return json(res,400,{ok:false,error:'INVALID_ADMIN'});const created=await supabaseFetch('admins',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({username,display_name:display,role:newRole,password_hash:passwordHash(password),active:true})});await audit(actor,'CREATE_ADMIN',username,{role:newRole},req);return json(res,200,{ok:true,admin:created?.[0]?{id:created[0].id,username:created[0].username,display_name:created[0].display_name,role:created[0].role,active:created[0].active}:null})}
 if(action==='set_admin_active'){if(!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});await supabaseFetch(`admins?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({active:Boolean(b.active)})});await audit(actor,'SET_ADMIN_ACTIVE',id,{active:Boolean(b.active)},req);return json(res,200,{ok:true})}
 return json(res,400,{ok:false,error:'UNKNOWN_ACTION'});
 }catch(error){console.error(error?.stack||error?.message||error);return json(res,500,{ok:false,error:'ADMIN_SERVER_ERROR'});}};
