const crypto=require('node:crypto');const{json,env,randomKey,sign,verifySession,setCookie,clearCookie,supabaseFetch}=require('./_lib');
const perms={OWNER:new Set(['read','keys','users','bot','api','audit','admins']),ADMIN:new Set(['read','keys','users','bot','api','audit']),SUPPORT:new Set(['read','keys_reset','users']),VIEWER:new Set(['read'])};
const body=req=>req.body||{};const ip=req=>String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||null;const ua=req=>String(req.headers['user-agent']||'').slice(0,300)||null;const int=(v,min,max,fallback)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):fallback};
const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const passwordHash=password=>{const salt=crypto.randomBytes(16).toString('base64url');return `scrypt$${salt}$${crypto.scryptSync(String(password),salt,64).toString('base64url')}`};
function passwordOk(password,stored){try{const[,salt,key]=String(stored||'').split('$');if(!salt||!key)return false;const got=crypto.scryptSync(String(password),salt,64).toString('base64url');return crypto.timingSafeEqual(Buffer.from(got),Buffer.from(key))}catch{return false}}
async function audit(actor,action,target,detail={},req){await supabaseFetch('admin_audit',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({action,actor,target:target==null?null:String(target),detail,ip_address:ip(req),user_agent:ua(req)})}).catch(()=>{})}
async function adminSession(req){const s=verifySession(req);if(!s?.sid||!s?.adminId)return null;const rows=await supabaseFetch(`admin_sessions?session_hash=eq.${encodeURIComponent(hash(s.sid))}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=id,admin_id&limit=1`).catch(()=>[]);if(!rows?.length)return null;const admins=await supabaseFetch(`admins?id=eq.${Number(s.adminId)}&active=eq.true&select=id,username,display_name,role,active,avatar_url,language,timezone,created_at,last_login_at,last_ip,last_user_agent&limit=1`).catch(()=>[]);if(!admins?.length)return null;await supabaseFetch(`admin_sessions?id=eq.${rows[0].id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_seen_at:new Date().toISOString()})}).catch(()=>{});return{session:s,admin:admins[0],sessionId:rows[0].id}}
async function createSession(admin,req){const sid=crypto.randomBytes(32).toString('base64url');const expires=new Date(Date.now()+12*3600000).toISOString();await supabaseFetch('admin_sessions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({admin_id:admin.id,session_hash:hash(sid),expires_at:expires,ip_address:ip(req),user_agent:ua(req)})});setCookie(req.res,sign({sub:admin.username,adminId:admin.id,role:admin.role,sid}));}
const allow=(role,p)=>!!perms[role]?.has(p);
async function ensureOwner(username,password,req){const rows=await supabaseFetch(`admins?username=eq.${encodeURIComponent(username)}&select=*&limit=1`).catch(()=>[]);if(rows?.[0])return rows[0].active&&passwordOk(password,rows[0].password_hash)?rows[0]:null;const created=await supabaseFetch('admins',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({username,display_name:username,role:'OWNER',password_hash:passwordHash(password),last_login_at:new Date().toISOString(),last_ip:ip(req),last_user_agent:ua(req)})});return created?.[0]||null}
async function telegramStatus(){try{const token=env('TELEGRAM_BOT_TOKEN');const me=await fetch(`https://api.telegram.org/bot${token}/getMe`).then(r=>r.json());const wh=await fetch(`https://api.telegram.org/bot${token}/getWebhookInfo`).then(r=>r.json());return{online:!!me?.ok,bot_name:me?.result?.first_name||null,username:me?.result?.username||null,webhook:!!wh?.ok&&!!wh?.result?.url,pending:wh?.result?.pending_update_count||0,last_error:wh?.result?.last_error_message||null,last_error_at:wh?.result?.last_error_date?new Date(wh.result.last_error_date*1000).toISOString():null}}catch{return{online:false,webhook:false,pending:0,last_error:'UNAVAILABLE'}}}
module.exports=async function handler(req,res){req.res=res;try{
 if(req.method==='POST'&&body(req).action==='login'){const b=body(req),username=String(b.username||'').trim(),password=String(b.password||'');if(!username||!password)return json(res,400,{ok:false,error:'INVALID_LOGIN'});const rl=await supabaseFetch('rpc/consume_rate_limit',{method:'POST',body:JSON.stringify({p_bucket:'admin-login:'+hash(ip(req)||'unknown'),p_limit:8,p_window_seconds:300})}).catch(()=>null);if(rl?.allowed===false)return json(res,429,{ok:false,error:'LOGIN_RATE_LIMITED'});let admin=null;if(username===env('ADMIN_USERNAME')&&password===env('ADMIN_PASSWORD'))admin=await ensureOwner(username,password,req);if(!admin){const rows=await supabaseFetch(`admins?username=eq.${encodeURIComponent(username)}&active=eq.true&select=*&limit=1`).catch(()=>[]);if(rows?.[0]&&passwordOk(password,rows[0].password_hash))admin=rows[0]}if(!admin)return json(res,401,{ok:false,error:'INVALID_LOGIN'});await supabaseFetch(`admins?id=eq.${admin.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_login_at:new Date().toISOString(),last_ip:ip(req),last_user_agent:ua(req)})}).catch(()=>{});await createSession(admin,req);await audit(admin.username,'LOGIN',admin.id,{},req);return json(res,200,{ok:true,user:admin.username,role:admin.role,display_name:admin.display_name})}
 if(req.method==='POST'&&body(req).action==='logout'){const s=verifySession(req);if(s?.sid)await supabaseFetch(`admin_sessions?session_hash=eq.${encodeURIComponent(hash(s.sid))}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})}).catch(()=>{});clearCookie(res);return json(res,200,{ok:true})}
 const ctx=await adminSession(req);if(!ctx)return json(res,401,{ok:false,error:'UNAUTHORIZED'});const actor=ctx.admin.username,role=ctx.admin.role;
 if(req.method==='GET'){const[allKeys,checks,users,tokens,audits,notes,admins,sessions,bot,shorteners,blo]=await Promise.all([supabaseFetch('app_keys?select=id,key_code,key_fingerprint,status,duration_hours,expires_at,telegram_user_id,telegram_username,max_devices,max_checks,activated_at,last_checked_at,check_count,created_at&order=created_at.desc&limit=1000'),supabaseFetch('key_checks?select=id,key_id,result,app_version,ip_address,created_at&order=created_at.desc&limit=500'),supabaseFetch('telegram_users?select=telegram_user_id,username,first_name,last_name,last_seen_at,created_at&order=last_seen_at.desc&limit=500'),supabaseFetch('key_claim_tokens?select=id,telegram_user_id,telegram_username,status,expires_at,used_at,created_at&order=created_at.desc&limit=300'),supabaseFetch('admin_audit?select=id,action,actor,target,detail,ip_address,user_agent,created_at&order=created_at.desc&limit=300'),supabaseFetch('notifications?select=id,severity,title,message,read_at,created_at&order=created_at.desc&limit=100'),allow(role,'admins')?supabaseFetch('admins?select=id,username,display_name,role,active,created_at,last_login_at,last_ip,last_user_agent&order=created_at.desc&limit=100'):Promise.resolve([]),allow(role,'admins')?supabaseFetch(`admin_sessions?admin_id=eq.${ctx.admin.id}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=id,created_at,last_seen_at,expires_at,ip_address,user_agent&order=last_seen_at.desc&limit=50`):Promise.resolve([]),supabaseFetch('bot_settings?select=*&limit=1'),supabaseFetch('shortener_configs?provider=eq.vuotlink&select=id,provider,enabled,base_url,sort_order,updated_at&limit=1'),supabaseFetch('bot_blocks?select=telegram_user_id,created_at,reason,blocked_by&limit=500')]);const botApi=await telegramStatus();return json(res,200,{ok:true,user:actor,role,admin:ctx.admin,keys:allKeys||[],checks:checks||[],users:users||[],claim_tokens:tokens||[],audit:audits||[],notifications:notes||[],admins:admins||[],sessions:sessions||[],bot:bot?.[0]||null,bot_status:botApi,blocked_users:blo||[],shorteners:shorteners||[],api:{provider:'Supabase',rpc:'check_key',endpoint:`${env('SUPABASE_URL')}/rest/v1/rpc/check_key`,method:'POST',body:{p_key:'KEY',p_device_id:'DEVICE_ID',p_app_version:'1.0.0'}}})}
 if(req.method!=='POST')return json(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'});const b=body(req),action=b.action;if(action==='create_key'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const hours=int(b.duration_hours,1,8760,24),devices=int(b.max_devices,1,100,1),checks=int(b.max_checks,0,1000000000,0),length=int(b.key_length,12,20,16);for(let i=0;i<8;i++){const code=randomKey(length);try{const created=await supabaseFetch('app_keys',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({key_code:code,key_fingerprint:hash(code),key_scope:'quick',status:'ACTIVE',duration_hours:hours,expires_at:new Date(Date.now()+hours*3600000).toISOString(),max_devices:devices,max_checks:checks,check_count:0})});await audit(actor,'CREATE_KEY',hash(code),{hours,devices,checks,length},req);return json(res,200,{ok:true,key:created?.[0]})}catch(e){if(!String(e.message||'').toLowerCase().includes('duplicate'))throw e}}throw new Error('KEY_GENERATION_FAILED')}
 if(action==='update_key'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0),patch={};if(!id)return json(res,400,{ok:false,error:'INVALID_ID'});if(b.duration_hours!==undefined){const h=int(b.duration_hours,1,8760,24);patch.duration_hours=h;patch.expires_at=new Date(Date.now()+h*3600000).toISOString()}if(b.max_devices!==undefined)patch.max_devices=int(b.max_devices,1,100,1);if(b.max_checks!==undefined)patch.max_checks=int(b.max_checks,0,1000000000,0);if(['CREATED','ACTIVE','DISABLED','EXPIRED','LIMIT_REACHED','REACTIVATED'].includes(b.status))patch.status=b.status;if(!Object.keys(patch).length)return json(res,400,{ok:false,error:'NO_CHANGES'});const updated=await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});await audit(actor,'UPDATE_KEY',id,{patch},req);return json(res,200,{ok:true,key:updated?.[0]||null})}
 if(action==='reset_device'){if(!allow(role,'keys_reset')&&!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({device_id_hash:null,activated_device_id_hash:null,activated_at:null})});await audit(actor,'RESET_DEVICE',id,{},req);return json(res,200,{ok:true})}
 if(action==='reset_checks'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({check_count:0,status:'ACTIVE'})});await audit(actor,'RESET_CHECKS',id,{},req);return json(res,200,{ok:true})}
 if(action==='set_status'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0),status=['CREATED','ACTIVE','DISABLED','EXPIRED','LIMIT_REACHED','REACTIVATED'].includes(b.status)?b.status:'DISABLED';await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status})});await audit(actor,'SET_KEY_STATUS',id,{status},req);return json(res,200,{ok:true})}
 if(action==='delete_key'){if(!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);await supabaseFetch(`app_keys?id=eq.${id}`,{method:'DELETE'});await audit(actor,'DELETE_KEY',id,{},req);return json(res,200,{ok:true})}
 if(action==='bulk_key_action'){if(!allow(role,'keys'))return json(res,403,{ok:false,error:'FORBIDDEN'});const ids=Array.isArray(b.ids)?b.ids.map(x=>int(x,1,2147483647,0)).filter(Boolean):[];if(ids.length>100)return json(res,400,{ok:false,error:'TOO_MANY_KEYS'});const op=String(b.operation||'');if(op==='delete'&&!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});for(const id of ids){if(op==='reset_device')await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({device_id_hash:null,activated_device_id_hash:null,activated_at:null})});else if(op==='disable'||op==='enable')await supabaseFetch(`app_keys?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:op==='enable'?'ACTIVE':'DISABLED'})});else if(op==='delete')await supabaseFetch(`app_keys?id=eq.${id}`,{method:'DELETE'});else return json(res,400,{ok:false,error:'UNKNOWN_BULK_OPERATION'})}await audit(actor,'BULK_KEY_ACTION',null,{operation:op,count:ids.length},req);return json(res,200,{ok:true,count:ids.length})}
 if(action==='save_shortener'){if(!allow(role,'bot'))return json(res,403,{ok:false,error:'FORBIDDEN'});const enabled=Boolean(b.enabled),baseUrl=String(b.base_url||'https://vuotlink.xyz/api').trim()||'https://vuotlink.xyz/api',token=String(b.api_token||'').trim(),patch={enabled,base_url:baseUrl,sort_order:1,updated_at:new Date().toISOString()};if(token)patch.api_token=token;await supabaseFetch('shortener_configs?provider=eq.vuotlink',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(patch)});await audit(actor,'SAVE_SHORTENER','vuotlink',{enabled,baseUrl,tokenChanged:Boolean(token)},req);return json(res,200,{ok:true})}
 if(action==='block_user'||action==='unblock_user'){if(!allow(role,'users'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=Number(b.telegram_user_id);if(!id)return json(res,400,{ok:false,error:'INVALID_USER'});if(action==='block_user')await supabaseFetch('bot_blocks',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({telegram_user_id:id,reason:String(b.reason||'Blocked by admin'),blocked_by:actor})});else await supabaseFetch(`bot_blocks?telegram_user_id=eq.${id}`,{method:'DELETE'});await audit(actor,action==='block_user'?'BLOCK_TELEGRAM_USER':'UNBLOCK_TELEGRAM_USER',id,{},req);return json(res,200,{ok:true})}
 if(action==='create_admin'){if(!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});const username=String(b.username||'').trim(),password=String(b.password||''),display=String(b.display_name||username).trim(),newRole=['ADMIN','SUPPORT','VIEWER'].includes(b.role)?b.role:'VIEWER';if(username.length<3||password.length<10)return json(res,400,{ok:false,error:'WEAK_ADMIN_CREDENTIALS'});const rows=await supabaseFetch('admins',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({username,display_name:display,role:newRole,password_hash:passwordHash(password),active:true})});await audit(actor,'CREATE_ADMIN',username,{role:newRole},req);return json(res,200,{ok:true,admin:rows?.[0]||null})}
 if(action==='toggle_admin'){if(!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});const id=int(b.id,1,2147483647,0);if(id===ctx.admin.id)return json(res,400,{ok:false,error:'CANNOT_DISABLE_SELF'});await supabaseFetch(`admins?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({active:Boolean(b.active)})});await audit(actor,'TOGGLE_ADMIN',id,{active:Boolean(b.active)},req);return json(res,200,{ok:true})}
 if(action==='revoke_session'){if(!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});await supabaseFetch(`admin_sessions?id=eq.${encodeURIComponent(String(b.id||''))}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});return json(res,200,{ok:true})}
 if(action==='logout_all'){if(!allow(role,'admins'))return json(res,403,{ok:false,error:'FORBIDDEN'});await supabaseFetch(`admin_sessions?admin_id=eq.${ctx.admin.id}&revoked_at=is.null`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});clearCookie(res);return json(res,200,{ok:true})}
 if(action==='mark_notification_read'){const id=int(b.id,1,2147483647,0);await supabaseFetch(`notifications?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({read_at:new Date().toISOString()})});return json(res,200,{ok:true})}
 return json(res,400,{ok:false,error:'UNKNOWN_ACTION'})
}catch(error){console.error(error);return json(res,500,{ok:false,error:'SERVER_ERROR'})}};